/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Trade_Program.Program;
import User.Users;

import javax.swing.*;

/**
 *
 * @author AH
 */
public class ResetPass extends javax.swing.JFrame {

    /**
     * Creates new form ResetPass
     */
    public ResetPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        UserRstLbl = new javax.swing.JLabel();
        UserRstTb = new javax.swing.JTextField();
        NewPassLbl = new javax.swing.JLabel();
        NewPassTb = new javax.swing.JPasswordField();
        ResetPassBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setText("Reset Password");

        UserRstLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        UserRstLbl.setText("Username:");

        UserRstTb.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        NewPassLbl.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        NewPassLbl.setText("New Password:");

        NewPassTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewPassTbActionPerformed(evt);
            }
        });

        ResetPassBtn.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        ResetPassBtn.setText("Reset");
        ResetPassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetPassBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(NewPassLbl)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(UserRstLbl)
                                        .addGap(31, 31, 31)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(UserRstTb)
                                    .addComponent(NewPassTb, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(149, 149, 149))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ResetPassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(229, 229, 229))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel5)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserRstLbl)
                    .addComponent(UserRstTb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewPassLbl)
                    .addComponent(NewPassTb, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(ResetPassBtn)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewPassTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewPassTbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewPassTbActionPerformed

    private void ResetPassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetPassBtnActionPerformed
        // TODO add your handling code here:
        if(UserRstTb.getText().isEmpty() || NewPassTb.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Enter Missing Information");
        }else{
            try{
                Program.client.sendData(Users.resetPass(UserRstTb.getText(), NewPassTb.getText()));
                JOptionPane.showMessageDialog(this,"Password Updated");
                UserRstTb.setText("");
                NewPassTb.setText("");
            }catch (Exception e){

            }
        }
    }//GEN-LAST:event_ResetPassBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NewPassLbl;
    private javax.swing.JPasswordField NewPassTb;
    private javax.swing.JButton ResetPassBtn;
    private javax.swing.JLabel UserRstLbl;
    private javax.swing.JTextField UserRstTb;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
